import AnimatedText from '@/components/AnimatedText';
import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import sungamaxLogo from '../../public/images/logos/sungamaxlogo.png';
import { LinkArrow } from '@/components/Icons';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sungamax</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={sungamaxLogo}
                alt="Sungamax Logo"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="To elevate the spiritual and financial well-being of humanity."
                className="!text-5xl !text-left"
              />
              <p className="my-4 text-base text-pcolor font-medium">
                We aim to provide high-impact easy business consultation, trade
                and investment that contribute to the creation of wealth,
                building the nation & assuring global well-being
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/about"
                  className="flex items-center bg-lightPurple text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-darkGrey border-2 border-solid border-transparent hover:border-lightPurple"
                >
                  Who We Are
                  <LinkArrow className={'w-5 ml-1'} />
                </Link>
                {/* <Link
                  href="/contact"
                  target={'_blank'}
                  className="ml-4 text-lg font-medium capitalize text-pcolor underline"
                >
                  Contact
                </Link> */}
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
